// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.0
// source: replication/proto/replication.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReplicateService_ReplicationConnect_FullMethodName = "/replication.ReplicateService/ReplicationConnect"
	ReplicateService_SnapshotConnect_FullMethodName    = "/replication.ReplicateService/SnapshotConnect"
)

// ReplicateServiceClient is the client API for ReplicateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicateServiceClient interface {
	ReplicationConnect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReplicationStreamConnectionRequest, ReplicationStreamConnectionResponse], error)
	SnapshotConnect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SnapshotRequest, SnapshotResponse], error)
}

type replicateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicateServiceClient(cc grpc.ClientConnInterface) ReplicateServiceClient {
	return &replicateServiceClient{cc}
}

func (c *replicateServiceClient) ReplicationConnect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReplicationStreamConnectionRequest, ReplicationStreamConnectionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReplicateService_ServiceDesc.Streams[0], ReplicateService_ReplicationConnect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReplicationStreamConnectionRequest, ReplicationStreamConnectionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReplicateService_ReplicationConnectClient = grpc.BidiStreamingClient[ReplicationStreamConnectionRequest, ReplicationStreamConnectionResponse]

func (c *replicateServiceClient) SnapshotConnect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SnapshotRequest, SnapshotResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReplicateService_ServiceDesc.Streams[1], ReplicateService_SnapshotConnect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SnapshotRequest, SnapshotResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReplicateService_SnapshotConnectClient = grpc.BidiStreamingClient[SnapshotRequest, SnapshotResponse]

// ReplicateServiceServer is the server API for ReplicateService service.
// All implementations must embed UnimplementedReplicateServiceServer
// for forward compatibility.
type ReplicateServiceServer interface {
	ReplicationConnect(grpc.BidiStreamingServer[ReplicationStreamConnectionRequest, ReplicationStreamConnectionResponse]) error
	SnapshotConnect(grpc.BidiStreamingServer[SnapshotRequest, SnapshotResponse]) error
	mustEmbedUnimplementedReplicateServiceServer()
}

// UnimplementedReplicateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplicateServiceServer struct{}

func (UnimplementedReplicateServiceServer) ReplicationConnect(grpc.BidiStreamingServer[ReplicationStreamConnectionRequest, ReplicationStreamConnectionResponse]) error {
	return status.Error(codes.Unimplemented, "method ReplicationConnect not implemented")
}
func (UnimplementedReplicateServiceServer) SnapshotConnect(grpc.BidiStreamingServer[SnapshotRequest, SnapshotResponse]) error {
	return status.Error(codes.Unimplemented, "method SnapshotConnect not implemented")
}
func (UnimplementedReplicateServiceServer) mustEmbedUnimplementedReplicateServiceServer() {}
func (UnimplementedReplicateServiceServer) testEmbeddedByValue()                          {}

// UnsafeReplicateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicateServiceServer will
// result in compilation errors.
type UnsafeReplicateServiceServer interface {
	mustEmbedUnimplementedReplicateServiceServer()
}

func RegisterReplicateServiceServer(s grpc.ServiceRegistrar, srv ReplicateServiceServer) {
	// If the following call panics, it indicates UnimplementedReplicateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReplicateService_ServiceDesc, srv)
}

func _ReplicateService_ReplicationConnect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReplicateServiceServer).ReplicationConnect(&grpc.GenericServerStream[ReplicationStreamConnectionRequest, ReplicationStreamConnectionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReplicateService_ReplicationConnectServer = grpc.BidiStreamingServer[ReplicationStreamConnectionRequest, ReplicationStreamConnectionResponse]

func _ReplicateService_SnapshotConnect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReplicateServiceServer).SnapshotConnect(&grpc.GenericServerStream[SnapshotRequest, SnapshotResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReplicateService_SnapshotConnectServer = grpc.BidiStreamingServer[SnapshotRequest, SnapshotResponse]

// ReplicateService_ServiceDesc is the grpc.ServiceDesc for ReplicateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplicateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "replication.ReplicateService",
	HandlerType: (*ReplicateServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReplicationConnect",
			Handler:       _ReplicateService_ReplicationConnect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SnapshotConnect",
			Handler:       _ReplicateService_SnapshotConnect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "replication/proto/replication.proto",
}
