syntax = "proto3";

package replication;

option go_package = "fluxKV/replication/proto";

service ReplicateService {
  rpc ReplicationConnect(stream ReplicationStreamConnectionRequest) returns (stream ReplicationStreamConnectionResponse);
  rpc SnapshotConnect(stream SnapshotRequest) returns (stream SnapshotResponse);
}

enum Command {
  NULL = 0;
  SET = 1;
  DEL = 2;
}

message ReplicationStreamConnectionRequest {
  string id = 1;
  uint64 offset = 2;
}

message ReplicationStreamConnectionResponse {
  bool success = 1;
  Command Op = 2;
  string key = 3;
  string value = 4;
  bool takeSnapshot = 5;
}

message SnapshotRequest {
  string id = 1;
}

message SnapshotResponse {
  Command Op = 1;
  string key = 2;
  string value = 3;
  uint64 offset = 4;
}