// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: replication/proto/replication.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command int32

const (
	Command_NULL Command = 0
	Command_SET  Command = 1
	Command_DEL  Command = 2
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0: "NULL",
		1: "SET",
		2: "DEL",
	}
	Command_value = map[string]int32{
		"NULL": 0,
		"SET":  1,
		"DEL":  2,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_replication_proto_replication_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_replication_proto_replication_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{0}
}

type ReplicationStreamConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationStreamConnectionRequest) Reset() {
	*x = ReplicationStreamConnectionRequest{}
	mi := &file_replication_proto_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationStreamConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationStreamConnectionRequest) ProtoMessage() {}

func (x *ReplicationStreamConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationStreamConnectionRequest.ProtoReflect.Descriptor instead.
func (*ReplicationStreamConnectionRequest) Descriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicationStreamConnectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReplicationStreamConnectionRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ReplicationStreamConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            Command                `protobuf:"varint,1,opt,name=Op,proto3,enum=replication.Command" json:"Op,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Offset        uint64                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Snapshot      bool                   `protobuf:"varint,5,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationStreamConnectionResponse) Reset() {
	*x = ReplicationStreamConnectionResponse{}
	mi := &file_replication_proto_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationStreamConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationStreamConnectionResponse) ProtoMessage() {}

func (x *ReplicationStreamConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationStreamConnectionResponse.ProtoReflect.Descriptor instead.
func (*ReplicationStreamConnectionResponse) Descriptor() ([]byte, []int) {
	return file_replication_proto_replication_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicationStreamConnectionResponse) GetOp() Command {
	if x != nil {
		return x.Op
	}
	return Command_NULL
}

func (x *ReplicationStreamConnectionResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReplicationStreamConnectionResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ReplicationStreamConnectionResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReplicationStreamConnectionResponse) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

var File_replication_proto_replication_proto protoreflect.FileDescriptor

const file_replication_proto_replication_proto_rawDesc = "" +
	"\n" +
	"#replication/proto/replication.proto\x12\vreplication\"L\n" +
	"\"ReplicationStreamConnectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\"\xa7\x01\n" +
	"#ReplicationStreamConnectionResponse\x12$\n" +
	"\x02Op\x18\x01 \x01(\x0e2\x14.replication.CommandR\x02Op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x04R\x06offset\x12\x1a\n" +
	"\bsnapshot\x18\x05 \x01(\bR\bsnapshot*%\n" +
	"\aCommand\x12\b\n" +
	"\x04NULL\x10\x00\x12\a\n" +
	"\x03SET\x10\x01\x12\a\n" +
	"\x03DEL\x10\x022\x8f\x01\n" +
	"\x10ReplicateService\x12{\n" +
	"\x12ReplicationConnect\x12/.replication.ReplicationStreamConnectionRequest\x1a0.replication.ReplicationStreamConnectionResponse(\x010\x01B\x1aZ\x18fluxKV/replication/protob\x06proto3"

var (
	file_replication_proto_replication_proto_rawDescOnce sync.Once
	file_replication_proto_replication_proto_rawDescData []byte
)

func file_replication_proto_replication_proto_rawDescGZIP() []byte {
	file_replication_proto_replication_proto_rawDescOnce.Do(func() {
		file_replication_proto_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_replication_proto_replication_proto_rawDesc), len(file_replication_proto_replication_proto_rawDesc)))
	})
	return file_replication_proto_replication_proto_rawDescData
}

var file_replication_proto_replication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_replication_proto_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_replication_proto_replication_proto_goTypes = []any{
	(Command)(0), // 0: replication.Command
	(*ReplicationStreamConnectionRequest)(nil),  // 1: replication.ReplicationStreamConnectionRequest
	(*ReplicationStreamConnectionResponse)(nil), // 2: replication.ReplicationStreamConnectionResponse
}
var file_replication_proto_replication_proto_depIdxs = []int32{
	0, // 0: replication.ReplicationStreamConnectionResponse.Op:type_name -> replication.Command
	1, // 1: replication.ReplicateService.ReplicationConnect:input_type -> replication.ReplicationStreamConnectionRequest
	2, // 2: replication.ReplicateService.ReplicationConnect:output_type -> replication.ReplicationStreamConnectionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_replication_proto_replication_proto_init() }
func file_replication_proto_replication_proto_init() {
	if File_replication_proto_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_replication_proto_replication_proto_rawDesc), len(file_replication_proto_replication_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_replication_proto_replication_proto_goTypes,
		DependencyIndexes: file_replication_proto_replication_proto_depIdxs,
		EnumInfos:         file_replication_proto_replication_proto_enumTypes,
		MessageInfos:      file_replication_proto_replication_proto_msgTypes,
	}.Build()
	File_replication_proto_replication_proto = out.File
	file_replication_proto_replication_proto_goTypes = nil
	file_replication_proto_replication_proto_depIdxs = nil
}
